export const THEME_COLOURS = [
  {
    name: "canvas",
    use: "Page background",
    dark: "#0B0E14",
    light: "#F4F6F8",
    swatch: "bg-canvas",
  },
  {
    name: "surface",
    use: "Cards, sidebar, header",
    dark: "#161B22",
    light: "#FFFFFF",
    swatch: "bg-surface",
  },
  {
    name: "surface-raised",
    use: "Hover and active chrome",
    dark: "#1C222C",
    light: "#EBEEF2",
    swatch: "bg-surface-raised",
  },
  {
    name: "line",
    use: "Default borders",
    dark: "#2A313C",
    light: "#D4DAE3",
    swatch: "bg-line",
  },
  {
    name: "line-strong",
    use: "Focus / strong dividers",
    dark: "#3A4352",
    light: "#B7C0CC",
    swatch: "bg-line-strong",
  },
  {
    name: "ink",
    use: "Primary text",
    dark: "#F4F6F8",
    light: "#12161C",
    swatch: "bg-ink",
  },
  {
    name: "ink-muted",
    use: "Labels",
    dark: "#9AA3B2",
    light: "#3F4754",
    swatch: "bg-ink-muted",
  },
  {
    name: "ink-faint",
    use: "Inactive / hints",
    dark: "#6B7382",
    light: "#66707E",
    swatch: "bg-ink-faint",
  },
  {
    name: "accent",
    use: "Links, charts, active",
    dark: "#A78BFA",
    light: "#7C5CDB",
    swatch: "bg-accent",
  },
  {
    name: "accent-strong",
    use: "Primary fill",
    dark: "#8B6CF6",
    light: "#6D4FE0",
    swatch: "bg-accent-strong",
  },
  {
    name: "plan-header",
    use: "Plan compare headers",
    dark: "#764DED",
    light: "#5B3CC9",
    swatch: "bg-plan-header",
  },
  {
    name: "success",
    use: "Positive",
    dark: "#34D399",
    light: "#0D7A4F",
    swatch: "bg-success",
  },
  {
    name: "danger",
    use: "Negative",
    dark: "#F07167",
    light: "#C4473E",
    swatch: "bg-danger",
  },
  {
    name: "warning",
    use: "Caution",
    dark: "#F5B942",
    light: "#9A6F0A",
    swatch: "bg-warning",
  },
] as const;

export type ThemePreviewScheme = "dark" | "light";
