-- Identity slice (roadmap 7 step 1). Prove the inbox. Auth tokens are
-- service-role only. Existing members are grandfathered verified.

alter table public.members
    add column if not exists email_verified_at timestamptz;

update public.members
    set email_verified_at = created_at
    where email_verified_at is null;

create table public.member_email_tokens (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.members (user_id) on delete cascade,
    purpose text not null check (purpose in ('verify', 'reset')),
    token_hash text not null,
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

create unique index member_email_tokens_hash_idx
    on public.member_email_tokens (token_hash);

create unique index member_email_tokens_one_unused_idx
    on public.member_email_tokens (user_id, purpose)
    where used_at is null;

create index member_email_tokens_user_purpose_created_idx
    on public.member_email_tokens (user_id, purpose, created_at desc);

alter table public.member_email_tokens enable row level security;

revoke all on table public.member_email_tokens from anon, authenticated;
revoke all on sequence public.member_email_tokens_id_seq from anon, authenticated;
