-- Phase 1 pipeline proof only. Do not add application tables here.

create table public.system_health (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamptz not null default now()
);

alter table public.system_health enable row level security;

insert into public.system_health (name)
values ('TBP');
