-- Desk members. Auth users are created by the admin app. Writes are service-role only.

create table public.members (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique references auth.users (id) on delete cascade,
    email text not null,
    name text not null check (char_length(name) between 1 and 80),
    role text not null check (role in ('member', 'admin')),
    status text not null check (status in ('active', 'disabled')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index members_email_lower_idx
    on public.members (lower(email));

create index members_role_idx on public.members (role);
create index members_status_idx on public.members (status);
create index members_created_at_idx on public.members (created_at desc);
create index members_name_idx on public.members (name);

insert into public.members (user_id, email, name, role, status)
select
    users.id,
    users.email,
    split_part(users.email, '@', 1),
    case
        when lower(users.email) = 'click.studio.admin@gmail.com' then 'admin'
        else 'member'
    end,
    'active'
from auth.users as users
where users.email is not null
on conflict (user_id) do nothing;

alter table public.members enable row level security;

create policy members_select_own_or_admin
    on public.members
    for select
    to authenticated
    using (
        user_id = auth.uid()
        or exists (
            select 1
            from public.app_admins
            where app_admins.user_id = auth.uid()
        )
    );

grant select on table public.members to authenticated;
grant usage, select on sequence public.members_id_seq to authenticated;

revoke insert, update, delete on table public.members from anon, authenticated;
