-- Phase 4: stacked paper rules. One enable switch, many entry/exit layers.

create table public.paper_engine_settings (
    user_id uuid primary key references auth.users (id) on delete cascade,
    enabled boolean not null default false,
    updated_at timestamptz not null default now()
);

insert into public.paper_engine_settings (user_id, enabled)
select user_id, enabled
from public.paper_rules;

create table public.paper_rule_layers (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    sort_order integer not null default 0,
    notional_usdt numeric not null default 10000 check (notional_usdt > 0),
    min_net_apr numeric,
    min_dte numeric,
    max_dte numeric,
    min_capacity_usdt numeric,
    max_open_count integer check (max_open_count is null or max_open_count > 0),
    max_open_notional_usdt numeric check (
        max_open_notional_usdt is null
        or max_open_notional_usdt > 0
    ),
    close_max_dte numeric,
    close_min_net_apr numeric,
    take_profit_pct numeric,
    stop_loss_pct numeric,
    check (
        min_dte is null
        or max_dte is null
        or min_dte <= max_dte
    )
);

insert into public.paper_rule_layers (
    user_id,
    sort_order,
    notional_usdt,
    min_net_apr,
    min_dte,
    max_dte,
    min_capacity_usdt,
    max_open_count,
    max_open_notional_usdt,
    close_max_dte,
    close_min_net_apr,
    take_profit_pct,
    stop_loss_pct
)
select
    user_id,
    0,
    notional_usdt,
    min_net_apr,
    min_dte,
    max_dte,
    min_capacity_usdt,
    max_open_count,
    max_open_notional_usdt,
    close_max_dte,
    close_min_net_apr,
    take_profit_pct,
    stop_loss_pct
from public.paper_rules;

drop table public.paper_rules;

alter table public.paper_rule_layers rename to paper_rules;

create index paper_rules_user_sort_idx
    on public.paper_rules (user_id, sort_order);

alter table public.paper_carries
    add column rule_id bigint references public.paper_rules (id) on delete set null;

alter table public.paper_engine_settings enable row level security;
alter table public.paper_rules enable row level security;

create policy paper_engine_settings_select_own
    on public.paper_engine_settings
    for select
    to authenticated
    using (user_id = auth.uid());

create policy paper_engine_settings_insert_own
    on public.paper_engine_settings
    for insert
    to authenticated
    with check (user_id = auth.uid());

create policy paper_engine_settings_update_own
    on public.paper_engine_settings
    for update
    to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

create policy paper_rules_select_own
    on public.paper_rules
    for select
    to authenticated
    using (user_id = auth.uid());

create policy paper_rules_insert_own
    on public.paper_rules
    for insert
    to authenticated
    with check (user_id = auth.uid());

create policy paper_rules_update_own
    on public.paper_rules
    for update
    to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

create policy paper_rules_delete_own
    on public.paper_rules
    for delete
    to authenticated
    using (user_id = auth.uid());

grant select, insert, update on table public.paper_engine_settings to authenticated;
grant select, insert, update, delete on table public.paper_rules to authenticated;

do $$
declare
    seq_name text;
begin
    seq_name := pg_get_serial_sequence('public.paper_rules', 'id');
    if seq_name is not null then
        execute format('grant usage, select on sequence %s to authenticated', seq_name);
    end if;
end $$;
