-- Phase 2: latest scan row per carry pair. Written by the app server only.

create table public.opportunities (
    id bigint generated by default as identity primary key,
    base_coin text not null,
    spot_symbol text not null,
    future_symbol text not null,
    delivery_time timestamptz not null,
    future_bid numeric not null,
    spot_ask numeric not null,
    executable_basis numeric not null,
    fee_rate numeric not null,
    net_basis numeric not null,
    net_apr numeric,
    capacity_usdt numeric not null,
    scanned_at timestamptz not null default now(),
    unique (spot_symbol, future_symbol)
);

alter table public.opportunities enable row level security;
