-- Append-only paper fills. One open and one close per carry today; later ticks
-- can add more clips on the same carry. No updates. No deletes.

create table public.paper_orders (
    id bigint generated by default as identity primary key,
    user_id uuid not null,
    carry_id bigint not null references public.paper_carries (id),
    side text not null check (side in ('open', 'close')),
    source text not null check (source in ('manual', 'engine')),
    trigger_reason text check (
        trigger_reason is null
        or trigger_reason in ('dte', 'mark_apr', 'take_profit', 'stop_loss')
    ),
    notional_usdt numeric not null check (notional_usdt > 0),
    filled_at timestamptz not null default now(),
    fill_basis numeric not null,
    theo_net_basis numeric,
    theo_net_apr numeric,
    theo_days_to_expiry numeric,
    theo_capacity_usdt numeric,
    theo_executable_basis numeric,
    theo_spot_ask numeric,
    theo_future_bid numeric,
    theo_fee_rate numeric,
    entry_size_type text
        check (entry_size_type is null or entry_size_type in ('fixed', 'dynamic')),
    exit_size_type text
        check (exit_size_type is null or exit_size_type in ('fixed', 'dynamic')),
    entry_min_net_apr numeric,
    entry_min_dte numeric,
    entry_max_dte numeric,
    entry_min_capacity_usdt numeric,
    entry_min_size_usdt numeric,
    close_max_dte numeric,
    close_min_net_apr numeric,
    take_profit_pct numeric,
    stop_loss_pct numeric
);

create index paper_orders_user_filled_idx
    on public.paper_orders (user_id, filled_at desc);

create index paper_orders_carry_filled_idx
    on public.paper_orders (carry_id, filled_at, id);

alter table public.paper_orders enable row level security;

create policy paper_orders_select_own
    on public.paper_orders
    for select
    to authenticated
    using (user_id = auth.uid());

create policy paper_orders_insert_own
    on public.paper_orders
    for insert
    to authenticated
    with check (user_id = auth.uid());

grant select, insert on table public.paper_orders to authenticated;
grant usage, select on sequence public.paper_orders_id_seq to authenticated;
revoke update, delete on table public.paper_orders from anon, authenticated;

insert into public.paper_orders (
    user_id,
    carry_id,
    side,
    source,
    trigger_reason,
    notional_usdt,
    filled_at,
    fill_basis,
    theo_net_basis,
    entry_size_type,
    exit_size_type,
    entry_min_net_apr,
    entry_min_dte,
    entry_max_dte,
    entry_min_capacity_usdt,
    entry_min_size_usdt,
    close_max_dte,
    close_min_net_apr,
    take_profit_pct,
    stop_loss_pct
)
select
    carries.user_id,
    carries.id,
    'open',
    coalesce(carries.source, 'manual'),
    null,
    carries.notional_usdt,
    carries.opened_at,
    carries.entry_basis,
    carries.entry_basis,
    carries.entry_size_type,
    carries.exit_size_type,
    carries.entry_min_net_apr,
    carries.entry_min_dte,
    carries.entry_max_dte,
    carries.entry_min_capacity_usdt,
    carries.entry_min_size_usdt,
    carries.close_max_dte,
    carries.close_min_net_apr,
    carries.take_profit_pct,
    carries.stop_loss_pct
from public.paper_carries as carries;

insert into public.paper_orders (
    user_id,
    carry_id,
    side,
    source,
    trigger_reason,
    notional_usdt,
    filled_at,
    fill_basis,
    theo_net_basis,
    entry_size_type,
    exit_size_type,
    entry_min_net_apr,
    entry_min_dte,
    entry_max_dte,
    entry_min_capacity_usdt,
    entry_min_size_usdt,
    close_max_dte,
    close_min_net_apr,
    take_profit_pct,
    stop_loss_pct
)
select
    carries.user_id,
    carries.id,
    'close',
    coalesce(carries.close_source, 'manual'),
    carries.close_reason,
    carries.notional_usdt,
    carries.closed_at,
    carries.exit_basis,
    carries.exit_basis,
    carries.entry_size_type,
    carries.exit_size_type,
    carries.entry_min_net_apr,
    carries.entry_min_dte,
    carries.entry_max_dte,
    carries.entry_min_capacity_usdt,
    carries.entry_min_size_usdt,
    carries.close_max_dte,
    carries.close_min_net_apr,
    carries.take_profit_pct,
    carries.stop_loss_pct
from public.paper_carries as carries
where carries.status = 'closed'
  and carries.closed_at is not null
  and carries.exit_basis is not null;
