-- Phase 3: paper cash-and-carry blotter. Authenticated users only. No deletes.

create table public.paper_carries (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    base_coin text not null,
    spot_symbol text not null,
    future_symbol text not null,
    delivery_time timestamptz not null,
    notional_usdt numeric not null check (notional_usdt > 0),
    entry_basis numeric not null,
    opened_at timestamptz not null default now(),
    status text not null default 'open' check (status in ('open', 'closed')),
    exit_basis numeric,
    closed_at timestamptz,
    realized_usdt numeric,
    days_held numeric,
    realized_apr numeric,
    check (
        (
            status = 'open'
            and exit_basis is null
            and closed_at is null
            and realized_usdt is null
        )
        or (
            status = 'closed'
            and exit_basis is not null
            and closed_at is not null
            and realized_usdt is not null
        )
    )
);

create unique index paper_carries_one_open_per_pair
    on public.paper_carries (user_id, spot_symbol, future_symbol)
    where status = 'open';

create index paper_carries_user_status_idx
    on public.paper_carries (user_id, status, opened_at desc);

alter table public.paper_carries enable row level security;

create policy paper_carries_select_own
    on public.paper_carries
    for select
    to authenticated
    using (user_id = auth.uid());

create policy paper_carries_insert_own
    on public.paper_carries
    for insert
    to authenticated
    with check (user_id = auth.uid());

create policy paper_carries_update_own
    on public.paper_carries
    for update
    to authenticated
    using (user_id = auth.uid())
    with check (user_id = auth.uid());

grant select, insert, update on table public.paper_carries to authenticated;
grant usage, select on sequence public.paper_carries_id_seq to authenticated;
