-- Append-only event logs and an admin allow-list. Writes are service-role only.

create table public.app_admins (
    user_id uuid primary key references auth.users (id) on delete cascade,
    created_at timestamptz not null default now()
);

create table public.event_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    level text not null check (level in ('info', 'warning', 'error')),
    scope text not null check (scope in ('system', 'strategy', 'trade')),
    event text not null check (
        char_length(event) between 1 and 64
        and event ~ '^[a-z][a-z0-9._-]*$'
    ),
    message text not null check (char_length(message) between 1 and 500),
    user_id uuid references auth.users (id) on delete set null,
    strategy text,
    data jsonb not null default '{}'::jsonb,
    check (jsonb_typeof(data) = 'object')
);

create index event_logs_created_at_idx
    on public.event_logs (created_at desc);

create index event_logs_scope_created_idx
    on public.event_logs (scope, created_at desc);

create index event_logs_user_created_idx
    on public.event_logs (user_id, created_at desc);

create index event_logs_event_created_idx
    on public.event_logs (event, created_at desc);

alter table public.app_admins enable row level security;
alter table public.event_logs enable row level security;

create policy app_admins_select_self
    on public.app_admins
    for select
    to authenticated
    using (user_id = auth.uid());

create policy event_logs_select_own_or_admin
    on public.event_logs
    for select
    to authenticated
    using (
        user_id = auth.uid()
        or exists (
            select 1
            from public.app_admins
            where app_admins.user_id = auth.uid()
        )
    );

grant select on table public.app_admins to authenticated;
grant select on table public.event_logs to authenticated;
grant usage, select on sequence public.event_logs_id_seq to authenticated;

revoke insert, update, delete on table public.app_admins from anon, authenticated;
revoke insert, update, delete on table public.event_logs from anon, authenticated;
