-- Transactional notifications (roadmap 6, step 2). Schema only.
-- Inbox and prefs key on members.user_id. Writes are service-role RPCs.
-- The app session check sits in TypeScript; TBP has no Supabase Auth JWT.

alter table public.platform_settings
    add column if not exists disabled_emails text[] not null default '{}';

create table public.user_notifications (
    id bigint generated by default as identity primary key,
    user_id uuid not null references public.members (user_id) on delete cascade,
    template text not null
        check (
            char_length(trim(template)) between 1 and 64
            and template ~ '^[a-z][a-z0-9_]*$'
        ),
    title text not null check (char_length(title) between 1 and 200),
    body text not null default '' check (char_length(body) <= 2000),
    href text not null default '/account/notifications'
        check (href ~ '^/[^/]' or href = '/account/notifications'),
    read_at timestamptz,
    created_at timestamptz not null default now()
);

create index user_notifications_user_created_idx
    on public.user_notifications (user_id, created_at desc);

create index user_notifications_user_unread_idx
    on public.user_notifications (user_id)
    where read_at is null;

create table public.user_notification_preferences (
    user_id uuid primary key references public.members (user_id) on delete cascade,
    disabled_emails text[] not null default '{}',
    disabled_in_app text[] not null default '{}',
    updated_at timestamptz not null default now()
);

create table public.email_dispatches (
    template text not null,
    entity_key text not null,
    sent_at timestamptz not null default now(),
    primary key (template, entity_key)
);

alter table public.user_notifications enable row level security;
alter table public.user_notification_preferences enable row level security;
alter table public.email_dispatches enable row level security;

revoke all on table public.user_notifications from anon, authenticated;
revoke all on table public.user_notification_preferences from anon, authenticated;
revoke all on table public.email_dispatches from anon, authenticated;

create function public.insert_user_notification(
    p_user_id uuid,
    p_template text,
    p_title text,
    p_body text,
    p_href text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_id bigint;
    v_href text;
begin
    if p_user_id is null
       or coalesce(trim(p_template), '') = ''
       or coalesce(trim(p_title), '') = '' then
        return null;
    end if;

    if not exists (
        select 1 from public.members where user_id = p_user_id
    ) then
        return null;
    end if;

    v_href := coalesce(nullif(trim(p_href), ''), '/account/notifications');
    if v_href !~ '^/[^/]' then
        v_href := '/account/notifications';
    end if;

    insert into public.user_notifications (
        user_id,
        template,
        title,
        body,
        href
    )
    values (
        p_user_id,
        trim(p_template),
        trim(p_title),
        coalesce(p_body, ''),
        v_href
    )
    returning id into v_id;

    return v_id;
end;
$$;

create function public.mark_user_notifications_read(
    p_user_id uuid,
    p_ids bigint[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if p_user_id is null then
        raise exception 'user_id is required';
    end if;

    update public.user_notifications
    set read_at = now()
    where user_id = p_user_id
      and read_at is null
      and (p_ids is null or id = any (p_ids));
end;
$$;

create function public.mark_user_notifications_unread(
    p_user_id uuid,
    p_ids bigint[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if p_user_id is null then
        raise exception 'user_id is required';
    end if;

    if p_ids is null or array_length(p_ids, 1) is null then
        return;
    end if;

    update public.user_notifications
    set read_at = null
    where user_id = p_user_id
      and read_at is not null
      and id = any (p_ids);
end;
$$;

create function public.upsert_user_notification_preferences(
    p_user_id uuid,
    p_disabled_emails text[],
    p_disabled_in_app text[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    if p_user_id is null then
        raise exception 'user_id is required';
    end if;

    insert into public.user_notification_preferences (
        user_id,
        disabled_emails,
        disabled_in_app,
        updated_at
    )
    values (
        p_user_id,
        coalesce(p_disabled_emails, '{}'),
        coalesce(p_disabled_in_app, '{}'),
        now()
    )
    on conflict (user_id) do update
        set disabled_emails = excluded.disabled_emails,
            disabled_in_app = excluded.disabled_in_app,
            updated_at = now();
end;
$$;

create function public.claim_email_dispatch(
    p_template text,
    p_entity_key text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
    inserted integer;
begin
    if coalesce(trim(p_template), '') = ''
       or coalesce(trim(p_entity_key), '') = '' then
        return false;
    end if;

    insert into public.email_dispatches (template, entity_key)
    values (trim(p_template), trim(p_entity_key))
    on conflict (template, entity_key) do nothing;

    get diagnostics inserted = row_count;
    return inserted > 0;
end;
$$;

revoke all on function public.insert_user_notification(uuid, text, text, text, text) from public;
revoke all on function public.mark_user_notifications_read(uuid, bigint[]) from public;
revoke all on function public.mark_user_notifications_unread(uuid, bigint[]) from public;
revoke all on function public.upsert_user_notification_preferences(uuid, text[], text[]) from public;
revoke all on function public.claim_email_dispatch(text, text) from public;

grant execute on function public.insert_user_notification(uuid, text, text, text, text) to service_role;
grant execute on function public.mark_user_notifications_read(uuid, bigint[]) to service_role;
grant execute on function public.mark_user_notifications_unread(uuid, bigint[]) to service_role;
grant execute on function public.upsert_user_notification_preferences(uuid, text[], text[]) to service_role;
grant execute on function public.claim_email_dispatch(text, text) to service_role;
